---
name: Automated Tests and Auto-Merge

on:
  pull_request:
    types:
      - opened

jobs:
  tests:
    name: Run Linter and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Auto-Merge PR
        if: success()  # This step will only run if the previous steps were successful (tests pass)
        run: |
          # Check if this action is running in the context of a pull request
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # Get the pull request number
            pr_number="${{ github.event.pull_request.number }}"
            
            # Use the GitHub CLI to merge the PR with --auto
            gh pr merge "$pr_number" --auto
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
